import { InventoryItem } from "./types";

/**
 * 28 realistic mock inventory items across all major categories.
 * Prices, stores, and dates are representative of real purchases.
 */
export const mockInventory: InventoryItem[] = [
  /* ═══════════ Electronics ═══════════ */
  {
    id: "el-001",
    name: 'MacBook Pro 16"',
    category: "Electronics",
    price: 2890,
    purchaseDate: new Date("2025-10-24"),
    store: "Apple Store",
    room: "Office",
    priority: "high",
    isInsured: true,
    isSentimental: false,
    receiptUrl: "/receipts/el-001.pdf",
  },
  {
    id: "el-002",
    name: 'LG C3 65" OLED TV',
    category: "Electronics",
    price: 1749.99,
    purchaseDate: new Date("2025-10-15"),
    store: "Best Buy",
    room: "Living Room",
    priority: "medium",
    isInsured: true,
    isSentimental: false,
  },
  {
    id: "el-003",
    name: "Sony A7IV Camera",
    category: "Electronics",
    price: 2499,
    purchaseDate: new Date("2025-08-03"),
    store: "B&H Photo",
    room: "Office",
    priority: "high",
    isInsured: true,
    isSentimental: false,
    receiptUrl: "/receipts/el-003.pdf",
  },
  {
    id: "el-004",
    name: "Apple TV 4K",
    category: "Electronics",
    price: 179,
    purchaseDate: new Date("2025-09-20"),
    store: "Apple Store",
    room: "Living Room",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },
  {
    id: "el-005",
    name: "Sonos Arc Soundbar",
    category: "Electronics",
    price: 899,
    purchaseDate: new Date("2025-07-12"),
    store: "Sonos.com",
    room: "Living Room",
    priority: "medium",
    isInsured: true,
    isSentimental: false,
  },
  {
    id: "el-006",
    name: "iPad Pro 12.9\"",
    category: "Electronics",
    price: 1299,
    purchaseDate: new Date("2025-06-18"),
    store: "Apple Store",
    room: "Bedroom",
    priority: "medium",
    isInsured: true,
    isSentimental: false,
  },

  /* ═══════════ Jewelry ═══════════ */
  {
    id: "jw-001",
    name: "Engagement Ring",
    category: "Jewelry",
    price: 18050,
    purchaseDate: new Date("2024-12-15"),
    store: "Tiffany & Co.",
    room: "Bedroom",
    priority: "critical",
    isInsured: true,
    isSentimental: true,
    receiptUrl: "/receipts/jw-001.pdf",
  },
  {
    id: "jw-002",
    name: "Cartier Love Bracelet",
    category: "Jewelry",
    price: 8050,
    purchaseDate: new Date("2025-10-03"),
    store: "Cartier",
    room: "Bathroom",
    priority: "high",
    isInsured: true,
    isSentimental: true,
    receiptUrl: "/receipts/jw-002.pdf",
  },
  {
    id: "jw-003",
    name: "Rolex Daydate 36mm",
    category: "Jewelry",
    price: 9500,
    purchaseDate: new Date("2024-06-01"),
    store: "Rolex Boutique",
    room: "Bedroom",
    priority: "high",
    isInsured: true,
    isSentimental: false,
    receiptUrl: "/receipts/jw-003.pdf",
  },
  {
    id: "jw-004",
    name: "Pearl Necklace",
    category: "Jewelry",
    price: 1200,
    purchaseDate: new Date("2023-05-10"),
    store: "Mikimoto",
    room: "Bedroom",
    priority: "medium",
    isInsured: false,
    isSentimental: true,
  },

  /* ═══════════ Furniture ═══════════ */
  {
    id: "fr-001",
    name: "Blue Eames Ottoman",
    category: "Furniture",
    price: 5020,
    purchaseDate: new Date("2025-04-22"),
    store: "Herman Miller",
    room: "Living Room",
    priority: "medium",
    isInsured: true,
    isSentimental: false,
  },
  {
    id: "fr-002",
    name: "Herman Miller Aeron Chair",
    category: "Furniture",
    price: 1395,
    purchaseDate: new Date("2025-01-10"),
    store: "Herman Miller",
    room: "Office",
    priority: "medium",
    isInsured: true,
    isSentimental: false,
  },
  {
    id: "fr-003",
    name: "Restoration Hardware Sofa",
    category: "Furniture",
    price: 4850,
    purchaseDate: new Date("2024-11-05"),
    store: "RH",
    room: "Living Room",
    priority: "medium",
    isInsured: true,
    isSentimental: false,
  },
  {
    id: "fr-004",
    name: "Walnut Dining Table",
    category: "Furniture",
    price: 2200,
    purchaseDate: new Date("2024-09-18"),
    store: "Article",
    room: "Dining Room",
    priority: "low",
    isInsured: true,
    isSentimental: false,
  },
  {
    id: "fr-005",
    name: "King Platform Bed Frame",
    category: "Furniture",
    price: 1899,
    purchaseDate: new Date("2024-08-02"),
    store: "West Elm",
    room: "Bedroom",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },
  {
    id: "fr-006",
    name: "Walnut Coffee Table",
    category: "Furniture",
    price: 875,
    purchaseDate: new Date("2025-03-15"),
    store: "CB2",
    room: "Living Room",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },

  /* ═══════════ Art & Decor ═══════════ */
  {
    id: "ad-001",
    name: "Abstract Oil Painting",
    category: "Art & Decor",
    price: 28400,
    purchaseDate: new Date("2024-03-28"),
    store: "Gagosian Gallery",
    room: "Living Room",
    priority: "high",
    isInsured: true,
    isSentimental: true,
    receiptUrl: "/receipts/ad-001.pdf",
  },
  {
    id: "ad-002",
    name: "Keith Haring Bearbrick 1000%",
    category: "Art & Decor",
    price: 799.99,
    purchaseDate: new Date("2025-08-25"),
    store: "StockX",
    room: "Office",
    priority: "medium",
    isInsured: false,
    isSentimental: true,
  },
  {
    id: "ad-003",
    name: "Ceramic Vase Set",
    category: "Art & Decor",
    price: 340,
    purchaseDate: new Date("2025-05-12"),
    store: "Crate & Barrel",
    room: "Dining Room",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },
  {
    id: "ad-004",
    name: "Wool Area Rug 8x10",
    category: "Art & Decor",
    price: 1250,
    purchaseDate: new Date("2025-02-08"),
    store: "Rugs USA",
    room: "Living Room",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },
  {
    id: "ad-005",
    name: "Bronze Sculpture",
    category: "Art & Decor",
    price: 3800,
    purchaseDate: new Date("2024-07-14"),
    store: "Artsy",
    room: "Hallway",
    priority: "medium",
    isInsured: true,
    isSentimental: true,
  },

  /* ═══════════ Appliances ═══════════ */
  {
    id: "ap-001",
    name: "Dyson V15 Detect",
    category: "Appliances",
    price: 749.99,
    purchaseDate: new Date("2025-09-05"),
    store: "Dyson.com",
    room: "Hallway",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },
  {
    id: "ap-002",
    name: "Le Creuset Cookware Set",
    category: "Appliances",
    price: 1100,
    purchaseDate: new Date("2025-06-20"),
    store: "Williams Sonoma",
    room: "Kitchen",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },
  {
    id: "ap-003",
    name: "Breville Barista Express",
    category: "Appliances",
    price: 699.95,
    purchaseDate: new Date("2025-04-01"),
    store: "Williams Sonoma",
    room: "Kitchen",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },
  {
    id: "ap-004",
    name: "Sub-Zero Refrigerator",
    category: "Appliances",
    price: 8999,
    purchaseDate: new Date("2024-02-14"),
    store: "AJ Madison",
    room: "Kitchen",
    priority: "medium",
    isInsured: true,
    isSentimental: false,
    receiptUrl: "/receipts/ap-004.pdf",
  },
  {
    id: "ap-005",
    name: "Miele Dishwasher",
    category: "Appliances",
    price: 1549,
    purchaseDate: new Date("2024-02-14"),
    store: "AJ Madison",
    room: "Kitchen",
    priority: "low",
    isInsured: true,
    isSentimental: false,
  },
  {
    id: "ap-006",
    name: "Vitamix A3500",
    category: "Appliances",
    price: 649.95,
    purchaseDate: new Date("2025-07-30"),
    store: "Vitamix.com",
    room: "Kitchen",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },
  {
    id: "ap-007",
    name: "Dyson Purifier Hot+Cool",
    category: "Appliances",
    price: 569.99,
    purchaseDate: new Date("2025-10-01"),
    store: "Dyson.com",
    room: "Bedroom",
    priority: "low",
    isInsured: false,
    isSentimental: false,
  },
  {
    id: "ap-008",
    name: "LG WashTower",
    category: "Appliances",
    price: 2499,
    purchaseDate: new Date("2024-05-22"),
    store: "Home Depot",
    room: "Garage",
    priority: "medium",
    isInsured: true,
    isSentimental: false,
    receiptUrl: "/receipts/ap-008.pdf",
  },
];

/* ═══════════════════ Derived constants ═══════════════════ */

/** Pre-computed for display — avoids recalculating on every render */
export const TOTAL_ITEMS = mockInventory.length;
export const TOTAL_VALUE = mockInventory.reduce((s, i) => s + i.price, 0);
export const INSURED_COUNT = mockInventory.filter((i) => i.isInsured).length;
export const INSURED_PERCENTAGE = Math.round(
  (INSURED_COUNT / TOTAL_ITEMS) * 100
);
export const CATEGORIES = Array.from(
  new Set(mockInventory.map((i) => i.category))
).sort();
export const ROOMS = Array.from(
  new Set(mockInventory.map((i) => i.room).filter(Boolean))
).sort() as string[];
